# Generated by Django 3.2.6 on 2023-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField()),
                ('sig_id', models.IntegerField()),
                ('source_ip', models.CharField(max_length=15)),
                ('destination_ip', models.CharField(max_length=15)),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
            ],
        ),
    ]
