# Generated by Django 3.2.6 on 2023-12-21 21:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=15)),
                ('destination_ip', models.CharField(max_length=15)),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('regex', models.TextField()),
                ('regex_hex', models.TextField()),
                ('protocol', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('http', 'HTTP'), ('bruteforce', 'Brute Force'), ('ssh', 'SSH')], max_length=50), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('http', 'HTTP'), ('bruteforce', 'Brute Force'), ('ssh', 'SSH')], max_length=50), size=None),
        ),
    ]
