# Generated by Django 3.2.6 on 2023-12-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231221_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='destination_ip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signature',
            name='destination_port',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signature',
            name='protocol',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signature',
            name='source_ip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signature',
            name='source_port',
            field=models.TextField(),
        ),
    ]
