CREATE TABLE IF NOT EXISTS public.acces_log_signature
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 200 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    pattern text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    tag text COLLATE pg_catalog."default",
    CONSTRAINT acces_log_signature_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.fuzzers_signature
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 300 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    pattern text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    tag text COLLATE pg_catalog."default",
    CONSTRAINT fuzzers_signature_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.files_signature
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 400 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    pattern text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    tag text COLLATE pg_catalog."default",
    CONSTRAINT files_signature_pkey PRIMARY KEY (id)
);